spring:
  datasource:
    url: jdbc:mysql://localhost:3306/osahaneat
    username: root
    password: Egoistic99!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
